
-- =============================================
-- AUTHOR:		ANAKAREN ROJAS
-- CREATE DATE: 08/22/2021
-- DESCRIPTION: PROCEDURE TO PULL A SINGLE MOVIE FROM FROM DATABASE BASED ON ID PROVIDED 
-- =============================================
USE BETTERTHANROTTENTOMATO;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[GETMOVIEBYID]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1 )
BEGIN
	DROP PROCEDURE [DBO].[GETMOVIEBYID];
END
GO

CREATE PROCEDURE [DBO].[GETMOVIEBYID] 
	-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE
	@ID BIGINT
AS
BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
	SET NOCOUNT ON;
	DECLARE @AVERAGERATING INT = (SELECT AVG(MR.RATING) FROM DBO.MOVIEREVIEWS MR WHERE MR.MOVIEID = @ID);

    -- INSERT STATEMENTS FOR PROCEDURE HERE
	SELECT TOP 1  *, @AVERAGERATING 
	FROM DBO.MOVIE M
	WHERE M.ID = @ID;
END
GO
