
-- =============================================
-- AUTHOR:		ANAKAREN ROJAS
-- CREATE DATE: 08/22/2021
-- DESCRIPTION:	PROCEDURE TO PULL REVIEWS BY MOVIE ID 
-- =============================================

USE BETTERTHANROTTENTOMATO;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[GETREVIEWSBYMOVIEID]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1 )
BEGIN
	DROP PROCEDURE [DBO].[GETREVIEWSBYMOVIEID];
END
GO

CREATE PROCEDURE [DBO].[GETREVIEWSBYMOVIEID] 
	-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE
	@MOVIEID BIGINT,
	@OFFSET INT,
	@PAGE INT
AS
BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
	SET NOCOUNT ON;

	DECLARE @TOTAL INT = (SELECT COUNT(*) FROM DBO.MOVIEREVIEWS WHERE MOVIEID = @MOVIEID); 

    -- INSERT STATEMENTS FOR PROCEDURE HERE
	SELECT 
	MR.ID,
	MR.COMMENT,
	MR.RATING,
	MR.MOVIEID,
	@TOTAL

	FROM DBO.MOVIEREVIEWS MR
	WHERE MR.MOVIEID = @MOVIEID
	ORDER BY MR.ID
	OFFSET ((@PAGE - 1) * @OFFSET) ROWS
	FETCH NEXT @OFFSET ROWS ONLY;
END
GO
