insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (18, 'morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh', 2, 'Pammie Abramow');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (17, 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in', 3, 'Daniele Bromige');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin', 2, 'Rahal Winslet');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (15, 'dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros', 3, 'Penelopa Abella');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis', 1, 'Dorelle Bibb');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (6, 'blandit ultrices enim lorem ipsum', 1, 'Noby Kittle');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 4, 'Albie Howsego');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'aliquam sit amet diam in magna bibendum imperdiet nullam orci', 5, 'Pet Papworth');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (11, 'luctus et ultrices posuere cubilia curae mauris viverra diam', 3, 'Jessee Betteridge');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices', 5, 'Nicol Becerra');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'mi sit amet lobortis sapien sapien non mi integer', 2, 'Marin Nussii');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (16, 'porttitor lorem id ligula suspendisse', 1, 'Carena Careswell');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (14, 'placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque', 4, 'Rene MacLeese');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (6, 'nam congue risus semper porta volutpat quam pede lobortis ligula sit amet', 2, 'Deni O''Hickey');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales', 5, 'Cos Drissell');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (20, 'integer pede justo lacinia eget tincidunt eget tempus', 5, 'Belinda Simeonov');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (18, 'libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut', 5, 'Hugo Woolveridge');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit', 4, 'Armin Casson');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (17, 'amet eros suspendisse accumsan tortor', 3, 'Chane Schuster');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (6, 'ut blandit non interdum in ante vestibulum', 2, 'Kristopher Malenoir');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac', 2, 'Sullivan McKomb');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget', 4, 'Bethanne Tapping');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (14, 'quis orci eget orci vehicula', 4, 'Karie Bloodworth');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum', 3, 'Vasili Jenken');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur', 5, 'Stefan Kasbye');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (17, 'nec nisi volutpat eleifend donec ut dolor morbi vel lectus', 2, 'Arliene Upson');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam', 5, 'Giovanna Sixsmith');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (20, 'enim in tempor turpis nec', 1, 'Anstice Thrasher');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id', 3, 'Theodore Townby');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (20, 'et eros vestibulum ac est lacinia nisi', 4, 'Carlynne Kirkpatrick');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (11, 'etiam pretium iaculis justo in hac habitasse platea dictumst', 3, 'Wileen Styche');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'proin interdum mauris non ligula pellentesque ultrices', 5, 'Cornela McNickle');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (18, 'odio donec vitae nisi nam', 4, 'Clarance Brownsell');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (16, 'et eros vestibulum ac est lacinia nisi', 5, 'Hubey Gillise');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'pede venenatis non sodales sed tincidunt', 4, 'Trudie Selwood');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (17, 'tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat', 1, 'Fred Whitsun');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (6, 'fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc', 1, 'Renee Bonnor');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (13, 'sagittis dui vel nisl duis ac', 1, 'Timmy Tibbles');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (10, 'mauris viverra diam vitae quam suspendisse potenti', 2, 'Anthea Gunston');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (14, 'luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus', 2, 'Abigail Sarsfield');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (13, 'luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur', 2, 'Goldie Rignoldes');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo', 3, 'Cyndi Altoft');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'magnis dis parturient montes nascetur ridiculus mus etiam vel', 1, 'Robbi Judson');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (17, 'nulla nunc purus phasellus in felis donec semper sapien', 2, 'Iosep Chamberlen');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis', 3, 'Mira Pleuman');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero', 4, 'Delora Leamy');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 5, 'Euphemia Kinnerk');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (11, 'rutrum nulla tellus in sagittis dui', 2, 'Ned Gayforth');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (12, 'erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in', 5, 'Antonie Trickett');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'tristique fusce congue diam id', 4, 'Bealle Sobczak');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (11, 'ac nulla sed vel enim sit', 1, 'Roddy Meo');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (16, 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis', 1, 'Melinde Roff');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (16, 'cursus urna ut tellus nulla ut erat id mauris', 5, 'Dore Saunton');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum', 5, 'Binni Feasby');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'orci luctus et ultrices posuere cubilia curae duis', 1, 'Brandtr Trevett');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (13, 'auctor sed tristique in tempus sit amet sem fusce consequat', 1, 'Steffi Scare');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse', 2, 'Perla Dumelow');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien', 4, 'Sada Ridpath');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus', 5, 'Cecilia Rosenqvist');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (20, 'fusce lacus purus aliquet at feugiat non pretium quis lectus', 4, 'Abdul Winnister');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit', 5, 'Christophe Bortolini');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', 1, 'Barton Felgate');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin', 5, 'Cad Boulger');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut', 4, 'Jorrie Gladtbach');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (17, 'consequat metus sapien ut nunc vestibulum ante ipsum primis in', 4, 'Sandro Nice');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo', 4, 'Haven Crumby');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (11, 'pede malesuada in imperdiet et commodo vulputate', 1, 'Debera Aizik');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (15, 'sit amet lobortis sapien sapien non mi integer ac neque', 1, 'Eimile Londing');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum', 4, 'Allister Jenicek');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'eget nunc donec quis orci eget orci vehicula condimentum', 4, 'Bengt Tarren');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'nonummy integer non velit donec diam neque vestibulum eget vulputate', 5, 'Erhard Bracknall');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'non interdum in ante vestibulum ante ipsum', 2, 'Delia MacTurlough');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum', 2, 'Chrissie Yarwood');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', 4, 'Jerrome McCarver');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'hendrerit at vulputate vitae nisl aenean lectus pellentesque', 3, 'Samson Unworth');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (20, 'erat quisque erat eros viverra eget congue eget semper rutrum', 5, 'Sue Chittleburgh');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum', 3, 'Cristy Sorrie');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'sit amet erat nulla tempus vivamus in felis eu', 3, 'Evania Dimnage');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (14, 'luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est', 3, 'Valdemar Pizzey');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 3, 'Julie Nucciotti');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (8, 'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper', 4, 'Zara Heinicke');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (15, 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam', 2, 'Charo Gaylord');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt', 1, 'Linea Eatttok');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (12, 'fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend', 2, 'Wain Pfleger');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'blandit mi in porttitor pede justo eu massa', 2, 'Babita Brumbie');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 2, 'Sibbie Screach');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'id luctus nec molestie sed justo', 2, 'Linnea Hartlebury');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus', 4, 'Win Ferrarin');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed', 4, 'Tab Izzat');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (13, 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean', 3, 'Luciana Hebden');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (10, 'lacus curabitur at ipsum ac tellus semper', 5, 'Marla Kunneke');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (8, 'tincidunt ante vel ipsum praesent blandit', 1, 'Garey Boissier');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'aliquam sit amet diam in magna bibendum imperdiet nullam', 5, 'Brittaney Wolfindale');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (16, 'nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus', 2, 'Aymer Wickson');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo', 5, 'Melly Izhaky');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac', 4, 'Corrinne Crocetti');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'morbi non lectus aliquam sit', 5, 'Cristiano Gorrissen');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (15, 'mollis molestie lorem quisque ut erat curabitur', 3, 'Regina Hibling');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 3, 'Charita Lettington');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (11, 'malesuada in imperdiet et commodo vulputate', 5, 'Prinz Minchin');