insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (18, 'morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh', 2, 'Pammie Abramow');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (17, 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in', 3, 'Daniele Bromige');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin', 2, 'Rahal Winslet');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (15, 'dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros', 3, 'Penelopa Abella');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis', 1, 'Dorelle Bibb');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (6, 'blandit ultrices enim lorem ipsum', 1, 'Noby Kittle');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 4, 'Albie Howsego');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'aliquam sit amet diam in magna bibendum imperdiet nullam orci', 5, 'Pet Papworth');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (11, 'luctus et ultrices posuere cubilia curae mauris viverra diam', 3, 'Jessee Betteridge');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices', 5, 'Nicol Becerra');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'mi sit amet lobortis sapien sapien non mi integer', 2, 'Marin Nussii');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (16, 'porttitor lorem id ligula suspendisse', 1, 'Carena Careswell');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (14, 'placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque', 4, 'Rene MacLeese');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (6, 'nam congue risus semper porta volutpat quam pede lobortis ligula sit amet', 2, 'Deni O''Hickey');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales', 5, 'Cos Drissell');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (20, 'integer pede justo lacinia eget tincidunt eget tempus', 5, 'Belinda Simeonov');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (18, 'libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut', 5, 'Hugo Woolveridge');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit', 4, 'Armin Casson');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (17, 'amet eros suspendisse accumsan tortor', 3, 'Chane Schuster');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (6, 'ut blandit non interdum in ante vestibulum', 2, 'Kristopher Malenoir');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac', 2, 'Sullivan McKomb');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget', 4, 'Bethanne Tapping');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (14, 'quis orci eget orci vehicula', 4, 'Karie Bloodworth');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum', 3, 'Vasili Jenken');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur', 5, 'Stefan Kasbye');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (17, 'nec nisi volutpat eleifend donec ut dolor morbi vel lectus', 2, 'Arliene Upson');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam', 5, 'Giovanna Sixsmith');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (20, 'enim in tempor turpis nec', 1, 'Anstice Thrasher');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id', 3, 'Theodore Townby');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (20, 'et eros vestibulum ac est lacinia nisi', 4, 'Carlynne Kirkpatrick');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (11, 'etiam pretium iaculis justo in hac habitasse platea dictumst', 3, 'Wileen Styche');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'proin interdum mauris non ligula pellentesque ultrices', 5, 'Cornela McNickle');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (18, 'odio donec vitae nisi nam', 4, 'Clarance Brownsell');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (16, 'et eros vestibulum ac est lacinia nisi', 5, 'Hubey Gillise');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'pede venenatis non sodales sed tincidunt', 4, 'Trudie Selwood');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (17, 'tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat', 1, 'Fred Whitsun');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (6, 'fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc', 1, 'Renee Bonnor');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (13, 'sagittis dui vel nisl duis ac', 1, 'Timmy Tibbles');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (10, 'mauris viverra diam vitae quam suspendisse potenti', 2, 'Anthea Gunston');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (14, 'luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus', 2, 'Abigail Sarsfield');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (13, 'luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur', 2, 'Goldie Rignoldes');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo', 3, 'Cyndi Altoft');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'magnis dis parturient montes nascetur ridiculus mus etiam vel', 1, 'Robbi Judson');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (17, 'nulla nunc purus phasellus in felis donec semper sapien', 2, 'Iosep Chamberlen');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis', 3, 'Mira Pleuman');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero', 4, 'Delora Leamy');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 5, 'Euphemia Kinnerk');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (11, 'rutrum nulla tellus in sagittis dui', 2, 'Ned Gayforth');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (12, 'erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in', 5, 'Antonie Trickett');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'tristique fusce congue diam id', 4, 'Bealle Sobczak');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (11, 'ac nulla sed vel enim sit', 1, 'Roddy Meo');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (16, 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis', 1, 'Melinde Roff');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (16, 'cursus urna ut tellus nulla ut erat id mauris', 5, 'Dore Saunton');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum', 5, 'Binni Feasby');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'orci luctus et ultrices posuere cubilia curae duis', 1, 'Brandtr Trevett');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (13, 'auctor sed tristique in tempus sit amet sem fusce consequat', 1, 'Steffi Scare');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse', 2, 'Perla Dumelow');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien', 4, 'Sada Ridpath');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus', 5, 'Cecilia Rosenqvist');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (20, 'fusce lacus purus aliquet at feugiat non pretium quis lectus', 4, 'Abdul Winnister');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit', 5, 'Christophe Bortolini');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', 1, 'Barton Felgate');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin', 5, 'Cad Boulger');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut', 4, 'Jorrie Gladtbach');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (17, 'consequat metus sapien ut nunc vestibulum ante ipsum primis in', 4, 'Sandro Nice');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo', 4, 'Haven Crumby');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (11, 'pede malesuada in imperdiet et commodo vulputate', 1, 'Debera Aizik');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (15, 'sit amet lobortis sapien sapien non mi integer ac neque', 1, 'Eimile Londing');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum', 4, 'Allister Jenicek');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'eget nunc donec quis orci eget orci vehicula condimentum', 4, 'Bengt Tarren');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'nonummy integer non velit donec diam neque vestibulum eget vulputate', 5, 'Erhard Bracknall');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'non interdum in ante vestibulum ante ipsum', 2, 'Delia MacTurlough');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum', 2, 'Chrissie Yarwood');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', 4, 'Jerrome McCarver');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'hendrerit at vulputate vitae nisl aenean lectus pellentesque', 3, 'Samson Unworth');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (20, 'erat quisque erat eros viverra eget congue eget semper rutrum', 5, 'Sue Chittleburgh');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum', 3, 'Cristy Sorrie');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'sit amet erat nulla tempus vivamus in felis eu', 3, 'Evania Dimnage');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (14, 'luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est', 3, 'Valdemar Pizzey');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 3, 'Julie Nucciotti');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (8, 'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper', 4, 'Zara Heinicke');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (15, 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam', 2, 'Charo Gaylord');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt', 1, 'Linea Eatttok');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (12, 'fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend', 2, 'Wain Pfleger');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'blandit mi in porttitor pede justo eu massa', 2, 'Babita Brumbie');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 2, 'Sibbie Screach');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'id luctus nec molestie sed justo', 2, 'Linnea Hartlebury');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus', 4, 'Win Ferrarin');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed', 4, 'Tab Izzat');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (13, 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean', 3, 'Luciana Hebden');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (10, 'lacus curabitur at ipsum ac tellus semper', 5, 'Marla Kunneke');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (8, 'tincidunt ante vel ipsum praesent blandit', 1, 'Garey Boissier');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'aliquam sit amet diam in magna bibendum imperdiet nullam', 5, 'Brittaney Wolfindale');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (16, 'nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus', 2, 'Aymer Wickson');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (9, 'erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo', 5, 'Melly Izhaky');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac', 4, 'Corrinne Crocetti');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (7, 'morbi non lectus aliquam sit', 5, 'Cristiano Gorrissen');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (15, 'mollis molestie lorem quisque ut erat curabitur', 3, 'Regina Hibling');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (19, 'dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 3, 'Charita Lettington');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (11, 'malesuada in imperdiet et commodo vulputate', 5, 'Prinz Minchin');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Mauris ullamcorper purus sit amet nulla.', 2, 'learsman0');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 3, 'ggherardesci1');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 4, 'echanning2');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 4, 'dbrouncker3');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Etiam pretium iaculis justo.', 4, 'chairyes4');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 4, 'acoursor5');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 3, 'dyakushkin6');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Morbi a ipsum.', 5, 'vmickan7');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 5, 'dkobera8');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 4, 'blattimore9');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 4, 'bchidlera');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 1, 'aredgraveb');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1, 'pferreirac');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 2, 'dbirtwisled');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 4, 'mhaskeye');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 2, 'tglowinskif');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Nulla suscipit ligula in lacus.', 3, 'ieassong');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'In congue. Etiam justo. Etiam pretium iaculis justo.', 5, 'tkopph');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 2, 'dscroytoni');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 4, 'rbaystingj');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 1, 'dnealk');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 2, 'plivickl');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'Nullam sit amet turpis elementum ligula vehicula consequat.', 4, 'tvittorim');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 3, 'llingnern');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', 4, 'tedmonsono');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', 2, 'sdealmeidap');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1, 'psilverthornq');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 4, 'nhogbourner');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'Aliquam non mauris. Morbi non lectus.', 3, 'ccasones');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 5, 'msedgewortht');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 4, 'hinettu');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', 2, 'dmailesv');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 2, 'hpavlasekw');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Morbi vel lectus in quam fringilla rhoncus.', 2, 'vwixeyx');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Sed accumsan felis. Ut at dolor quis odio consequat varius.', 5, 'mtysally');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 3, 'jorrz');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 5, 'toland10');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 1, 'cgodier11');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Pellentesque ultrices mattis odio.', 1, 'jlodemann12');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Donec ut dolor.', 1, 'tdufoure13');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Nulla nisl. Nunc nisl.', 3, 'hatwell14');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 2, 'malwen15');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Integer ac neque.', 3, 'malessandrucci16');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 5, 'lkordt17');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Integer a nibh. In quis justo.', 5, 'hsainteau18');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 5, 'ereicharz19');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 1, 'agammell1a');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 4, 'mhaffard1b');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 2, 'rhackworthy1c');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Integer ac neque.', 5, 'dshirrell1d');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 5, 'vconneely1e');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'In sagittis dui vel nisl.', 4, 'ibonifazio1f');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Cras pellentesque volutpat dui.', 4, 'abrierley1g');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 4, 'mstodhart1h');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Nulla nisl.', 3, 'amoncreif1i');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 3, 'aluscott1j');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Vestibulum ac est lacinia nisi venenatis tristique.', 2, 'achartre1k');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Maecenas rhoncus aliquam lacus.', 1, 'rmcgillecole1l');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 4, 'sscarsbrooke1m');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 3, 'shullyer1n');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 1, 'coxtaby1o');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 2, 'slevet1p');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 4, 'alanda1q');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 5, 'mbilbrooke1r');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 5, 'rmurrey1s');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 2, 'moughtright1t');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 3, 'squincey1u');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Duis bibendum. Morbi non quam nec dui luctus rutrum.', 5, 'mhenworth1v');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 3, 'rmollatt1w');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Donec semper sapien a libero.', 2, 'sbreissan1x');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 2, 'rbuick1y');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 5, 'hbunney1z');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 4, 'tredhole20');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 2, 'pheaven21');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Praesent blandit lacinia erat.', 2, 'egiampietro22');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 3, 'ltithecott23');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 1, 'sjakolevitch24');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 2, 'ctyrer25');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Curabitur in libero ut massa volutpat convallis.', 2, 'rsantori26');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 2, 'dwilshaw27');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 1, 'bdecent28');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 2, 'oarchbald29');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Duis consequat dui nec nisi volutpat eleifend.', 1, 'qlittlemore2a');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 2, 'vraleston2b');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, 'mcruickshank2c');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Vivamus vestibulum sagittis sapien.', 2, 'lboolsen2d');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'Morbi quis tortor id nulla ultrices aliquet.', 2, 'jsyalvester2e');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 2, 'imoffat2f');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Mauris lacinia sapien quis libero.', 3, 'gballham2g');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (5, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 4, 'kgrene2h');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'Vivamus tortor.', 3, 'ebilbrey2i');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 3, 'bgyurkovics2j');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 4, 'esaunton2k');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 1, 'mtayt2l');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (1, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 4, 'tvanner2m');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 4, 'jgartsyde2n');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (4, 'Praesent blandit lacinia erat.', 3, 'awimlett2o');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (3, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 4, 'kbetke2p');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 3, 'dmccuffie2q');
insert into dbo.moviereviews (MovieId, Comment, Rating, Username) values (2, 'Pellentesque eget nunc.', 4, 'pdonaldson2r');